if (document.getElementById) {
	var l1 = new WebFXTree('');
	var l2 = new WebFXTreeItem('Projektdatenbank: \'Abs_Box_Werte\'', 'abs_box_werte/toc.htm', l1);
		var l3 = new WebFXTreeItem('3d_drucker', 'abs_box_werte/3d_drucker/toc.htm', l2);
			var l4 = new WebFXTreeItem('3d_durckmessung1', 'abs_box_werte/3d_drucker/3d_durckmessung1/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/3d_drucker/3d_durckmessung1/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/3d_drucker/3d_durckmessung1/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/3d_drucker/3d_durckmessung1/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/3d_drucker/3d_durckmessung1/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm5', 'abs_box_werte/3d_drucker/3d_durckmessung1/2d-diagramm5_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm6', 'abs_box_werte/3d_drucker/3d_durckmessung1/2d-diagramm6_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('3druck_fortsetzung_lüften', 'abs_box_werte/3d_drucker/3druck_fortsetzung_lüften/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/3d_drucker/3druck_fortsetzung_lüften/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/3d_drucker/3druck_fortsetzung_lüften/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/3d_drucker/3druck_fortsetzung_lüften/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/3d_drucker/3druck_fortsetzung_lüften/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('abs_drcuk_intern_12_10', 'abs_box_werte/3d_drucker/abs_drcuk_intern_12_10/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/3d_drucker/abs_drcuk_intern_12_10/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/3d_drucker/abs_drcuk_intern_12_10/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/3d_drucker/abs_drcuk_intern_12_10/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/3d_drucker/abs_drcuk_intern_12_10/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm5', 'abs_box_werte/3d_drucker/abs_drcuk_intern_12_10/2d-diagramm5_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('hohetemp_messung_im_3d_ohne_abs', 'abs_box_werte/3d_drucker/hohetemp_messung_im_3d_ohne_abs/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/3d_drucker/hohetemp_messung_im_3d_ohne_abs/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('ABS_BOX', 'abs_box_werte/abs_box/toc.htm', l2);
			var l4 = new WebFXTreeItem('ABS_1s_box', 'abs_box_werte/abs_box/abs_1s_box/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/abs_box/abs_1s_box/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/abs_box/abs_1s_box/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/abs_box/abs_1s_box/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/abs_box/abs_1s_box/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm5', 'abs_box_werte/abs_box/abs_1s_box/2d-diagramm5_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('abs_box_12_10', 'abs_box_werte/abs_box/abs_box_12_10/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/abs_box/abs_box_12_10/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/abs_box/abs_box_12_10/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/abs_box/abs_box_12_10/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('Abs_filamentstück', 'abs_box_werte/abs_box/abs_filamentstück/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/abs_box/abs_filamentstück/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/abs_box/abs_filamentstück/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/abs_box/abs_filamentstück/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/abs_box/abs_filamentstück/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm5', 'abs_box_werte/abs_box/abs_filamentstück/2d-diagramm5_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('Abs_messug_ohne_vorlauf', 'abs_box_werte/abs_box/abs_messug_ohne_vorlauf/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/abs_box/abs_messug_ohne_vorlauf/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('ABS_messung_leicht', 'abs_box_werte/abs_box/abs_messung_leicht/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/abs_box/abs_messung_leicht/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('Vergleichssmessung', 'abs_box_werte/abs_box/vergleichssmessung/toc.htm', l3);
				var l5 = new WebFXTreeItem('petg_vergelichsmeesung', 'abs_box_werte/abs_box/vergleichssmessung/petg_vergelichsmeesung/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/abs_box/vergleichssmessung/petg_vergelichsmeesung/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
				var l5 = new WebFXTreeItem('pla_vergleichsmessung', 'abs_box_werte/abs_box/vergleichssmessung/pla_vergleichsmessung/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/abs_box/vergleichssmessung/pla_vergleichsmessung/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/abs_box/vergleichssmessung/pla_vergleichsmessung/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/abs_box/vergleichssmessung/pla_vergleichsmessung/2d-diagramm3_2d.htm', l5, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('Ausenluft', 'abs_box_werte/ausenluft/toc.htm', l2);
			var l4 = new WebFXTreeItem('aklimatisierung_nach_drausen', 'abs_box_werte/ausenluft/aklimatisierung_nach_drausen/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/ausenluft/aklimatisierung_nach_drausen/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('ausenluft_messung2_schwankungen', 'abs_box_werte/ausenluft/ausenluft_messung2_schwankungen/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/ausenluft/ausenluft_messung2_schwankungen/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/ausenluft/ausenluft_messung2_schwankungen/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('ausenluft_messung_gehäuse', 'abs_box_werte/ausenluft/ausenluft_messung_gehäuse/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/ausenluft/ausenluft_messung_gehäuse/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/ausenluft/ausenluft_messung_gehäuse/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/ausenluft/ausenluft_messung_gehäuse/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/ausenluft/ausenluft_messung_gehäuse/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm5', 'abs_box_werte/ausenluft/ausenluft_messung_gehäuse/2d-diagramm5_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('aussenluft_6_10_regen', 'abs_box_werte/ausenluft/aussenluft_6_10_regen/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/ausenluft/aussenluft_6_10_regen/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/ausenluft/aussenluft_6_10_regen/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/ausenluft/aussenluft_6_10_regen/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/ausenluft/aussenluft_6_10_regen/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm5', 'abs_box_werte/ausenluft/aussenluft_6_10_regen/2d-diagramm5_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('drausen_morgens', 'abs_box_werte/ausenluft/drausen_morgens/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/ausenluft/drausen_morgens/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/ausenluft/drausen_morgens/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/ausenluft/drausen_morgens/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('druckdata_abs2_alt', 'abs_box_werte/druckdata_abs2_alt/toc.htm', l2);
			new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/druckdata_abs2_alt/2d-diagramm_2d.htm', l3, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('druckdata_abs_alt', 'abs_box_werte/druckdata_abs_alt/toc.htm', l2);
			new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/druckdata_abs_alt/2d-diagramm_2d.htm', l3, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('kochmessung_1_anbraten', 'abs_box_werte/kochmessung_1_anbraten/toc.htm', l2);
			new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/kochmessung_1_anbraten/2d-diagramm_2d.htm', l3, '_resources/2ddiagram.gif');
			new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/kochmessung_1_anbraten/2d-diagramm2_2d.htm', l3, '_resources/2ddiagram.gif');
			new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/kochmessung_1_anbraten/2d-diagramm3_2d.htm', l3, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('Luft', 'abs_box_werte/luft/toc.htm', l2);
			var l4 = new WebFXTreeItem('Basis_messung', 'abs_box_werte/luft/basis_messung/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/basis_messung/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/luft/basis_messung/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/luft/basis_messung/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('gute_luft_12_10_test', 'abs_box_werte/luft/gute_luft_12_10_test/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/gute_luft_12_10_test/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('StadnertLuft_gute_qualität', 'abs_box_werte/luft/stadnertluft_gute_qualität/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/stadnertluft_gute_qualität/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/luft/stadnertluft_gute_qualität/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/luft/stadnertluft_gute_qualität/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('standert_luft_hoher_luftdurck', 'abs_box_werte/luft/standert_luft_hoher_luftdurck/toc.htm', l3);
				var l5 = new WebFXTreeItem('standert_luft_6_10', 'abs_box_werte/luft/standert_luft_hoher_luftdurck/standert_luft_6_10/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/standert_luft_hoher_luftdurck/standert_luft_6_10/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/luft/standert_luft_hoher_luftdurck/standert_luft_6_10/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/standert_luft_hoher_luftdurck/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('StandertBox_anderer_luftdruck', 'abs_box_werte/luft/standertbox_anderer_luftdruck/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/standertbox_anderer_luftdruck/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/luft/standertbox_anderer_luftdruck/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('Standertluft_nach_einigen_messungen', 'abs_box_werte/luft/standertluft_nach_einigen_messungen/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/standertluft_nach_einigen_messungen/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('test_mit_neuem_wert', 'abs_box_werte/luft/test_mit_neuem_wert/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/test_mit_neuem_wert/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('xxl_standert_messung', 'abs_box_werte/luft/xxl_standert_messung/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/luft/xxl_standert_messung/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/luft/xxl_standert_messung/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('lüften_fenster_gekippt', 'abs_box_werte/lüften_fenster_gekippt/toc.htm', l2);
			new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/lüften_fenster_gekippt/2d-diagramm_2d.htm', l3, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('Schlechte_luft', 'abs_box_werte/schlechte_luft/toc.htm', l2);
			var l4 = new WebFXTreeItem('schlechte_luft_Lueften_correktur_sensoren', 'abs_box_werte/schlechte_luft/schlechte_luft_lueften_correktur_sensoren/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/schlechte_luft/schlechte_luft_lueften_correktur_sensoren/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/schlechte_luft/schlechte_luft_lueften_correktur_sensoren/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/schlechte_luft/schlechte_luft_lueften_correktur_sensoren/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('schlechte_luft_Morgens', 'abs_box_werte/schlechte_luft/schlechte_luft_morgens/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/schlechte_luft/schlechte_luft_morgens/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/schlechte_luft/schlechte_luft_morgens/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/schlechte_luft/schlechte_luft_morgens/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/schlechte_luft/schlechte_luft_morgens/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('Schlechteluft_lüften', 'abs_box_werte/schlechte_luft/schlechteluft_lüften/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/schlechte_luft/schlechteluft_lüften/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/schlechte_luft/schlechteluft_lüften/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/schlechte_luft/schlechteluft_lüften/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/schlechte_luft/schlechteluft_lüften/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
		var l3 = new WebFXTreeItem('Zigaretenrauchmessungen', 'abs_box_werte/zigaretenrauchmessungen/toc.htm', l2);
			var l4 = new WebFXTreeItem('erstes_anzünden_zigarrete', 'abs_box_werte/zigaretenrauchmessungen/erstes_anzünden_zigarrete/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/erstes_anzünden_zigarrete/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/erstes_anzünden_zigarrete/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('Wohnzimmer', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/toc.htm', l3);
				var l5 = new WebFXTreeItem('wohnzimmermessung_6', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/wohnzimmermessung_6/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/wohnzimmermessung_6/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/wohnzimmermessung_6/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
				var l5 = new WebFXTreeItem('wohnzimmermessung_rauchen_7', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/wohnzimmermessung_rauchen_7/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/wohnzimmermessung_rauchen_7/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/wohnzimmermessung_rauchen_7/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/wohnzimmermessung_rauchen_7/2d-diagramm3_2d.htm', l5, '_resources/2ddiagram.gif');
				var l5 = new WebFXTreeItem('zigaretenrauch_wohnzimmer_5', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigaretenrauch_wohnzimmer_5/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigaretenrauch_wohnzimmer_5/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigaretenrauch_wohnzimmer_5/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigaretenrauch_wohnzimmer_5/2d-diagramm3_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigaretenrauch_wohnzimmer_5/2d-diagramm4_2d.htm', l5, '_resources/2ddiagram.gif');
				var l5 = new WebFXTreeItem('Zigarette_messung_wohnzimmer3_abstand_drüber', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarette_messung_wohnzimmer3_abstand_drüber/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarette_messung_wohnzimmer3_abstand_drüber/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarette_messung_wohnzimmer3_abstand_drüber/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarette_messung_wohnzimmer3_abstand_drüber/2d-diagramm3_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarette_messung_wohnzimmer3_abstand_drüber/2d-diagramm4_2d.htm', l5, '_resources/2ddiagram.gif');
				var l5 = new WebFXTreeItem('zigarettenrauch_raummessung_4_anderer_tag', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarettenrauch_raummessung_4_anderer_tag/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarettenrauch_raummessung_4_anderer_tag/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarettenrauch_raummessung_4_anderer_tag/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
				var l5 = new WebFXTreeItem('zigarrete_wohnzimmer_messung2', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarrete_wohnzimmer_messung2/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarrete_wohnzimmer_messung2/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/zigarrete_wohnzimmer_messung2/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
				var l5 = new WebFXTreeItem('ziggaretenrauch_raummessung_1', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/ziggaretenrauch_raummessung_1/toc.htm', l4);
					new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/ziggaretenrauch_raummessung_1/2d-diagramm_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/ziggaretenrauch_raummessung_1/2d-diagramm2_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/ziggaretenrauch_raummessung_1/2d-diagramm3_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/ziggaretenrauch_raummessung_1/2d-diagramm4_2d.htm', l5, '_resources/2ddiagram.gif');
					new WebFXTreeItem('2D-Diagramm5', 'abs_box_werte/zigaretenrauchmessungen/wohnzimmer/ziggaretenrauch_raummessung_1/2d-diagramm5_2d.htm', l5, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('Zigarentbox_messung2_starke_wirkung', 'abs_box_werte/zigaretenrauchmessungen/zigarentbox_messung2_starke_wirkung/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/zigarentbox_messung2_starke_wirkung/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/zigarentbox_messung2_starke_wirkung/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('zigaretenmessung_anderertag_box', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_anderertag_box/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_anderertag_box/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_anderertag_box/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_anderertag_box/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm4', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_anderertag_box/2d-diagramm4_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('zigaretenmessung_draußen_offen', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_draußen_offen/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_draußen_offen/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_draußen_offen/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/zigaretenrauchmessungen/zigaretenmessung_draußen_offen/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
			var l4 = new WebFXTreeItem('zigarretenrauch_messung_halboffen_anderer_raum', 'abs_box_werte/zigaretenrauchmessungen/zigarretenrauch_messung_halboffen_anderer_raum/toc.htm', l3);
				new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/zigaretenrauchmessungen/zigarretenrauch_messung_halboffen_anderer_raum/2d-diagramm_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/zigaretenrauchmessungen/zigarretenrauch_messung_halboffen_anderer_raum/2d-diagramm2_2d.htm', l4, '_resources/2ddiagram.gif');
				new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/zigaretenrauchmessungen/zigarretenrauch_messung_halboffen_anderer_raum/2d-diagramm3_2d.htm', l4, '_resources/2ddiagram.gif');
		new WebFXTreeItem('2D-Diagramm', 'abs_box_werte/2d-diagramm_2d.htm', l2, '_resources/2ddiagram.gif');
		new WebFXTreeItem('2D-Diagramm2', 'abs_box_werte/2d-diagramm2_2d.htm', l2, '_resources/2ddiagram.gif');
		new WebFXTreeItem('2D-Diagramm3', 'abs_box_werte/2d-diagramm3_2d.htm', l2, '_resources/2ddiagram.gif');
	document.write(l1);
}