/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"

#include "tflite-model/tflite_learn_729880_47_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_729880_5[] = { "Abs_box", "Abs_intern", "Außenluft", "Kochen", "Luft", "SchlechteLuft", "ZigaretenrauchBox", "ZigaretenrauchRaum" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_729880_49_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_729880_49_axes_size = 2;
ei_dsp_config_flatten_t ei_dsp_config_729880_49 = {
    49, // uint32_t blockId
    1, // int implementationVersion
    2, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true, // boolean kurtosis
    0 // int moving_avg_num_windows
};


EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_729880_50_axes[] = { 2 };
const uint32_t ei_dsp_config_729880_50_axes_size = 1;
ei_dsp_config_spectral_analysis_t ei_dsp_config_729880_50 = {
    50, // uint32_t blockId
    4, // int implementationVersion
    1, // int length of axes
    0.00000526274242f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    0.14453125f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    32, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    false, // boolean do-fft-overlap
    1, // int wavelet-level
    "rbio3.3", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_49[14] = { 32.23528122469738, 32.20088270855814, 32.27753099718122, 32.24075460938168, 0.028152816020109862, -0.10076771729155716, -0.6172424503447336, 35.512053543707395, 35.3759923053292, 35.654201876360844, 35.520013841617505, 0.11132642269901948, -0.014298167223183951, -2.444499495098778 };
const float ei_dn_standard_scaler_scale_49[14] = { 0.12192232198512006, 0.12176593771512995, 0.12211861841525296, 0.12211894459957241, 2.7150583963931196, 1.1807152412293345, 0.6199241887500109, 0.091381691920178, 0.09173177245102371, 0.09095083697507683, 0.0914838879614577, 1.871057756702609, 1.7285834897222085, 0.6437964848239681 };
const float ei_dn_standard_scaler_var_49[14] = { 67.2718776735561, 67.4447834841219, 67.05578259479103, 67.05542437820684, 0.13565682553266534, 0.7173145849214986, 2.6020931250807697, 119.75167882527803, 118.83939436218859, 120.88894847161166, 119.48428065913974, 0.28564433313774024, 0.33467192274901164, 2.412697075815377 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_49 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_49,
    .mean_data_len = 14,
    .scale_data = (float *)ei_dn_standard_scaler_scale_49,
    .scale_data_len = 14,
    .var_data = (float *)ei_dn_standard_scaler_var_49,
    .var_data_len = 14
};
ei_data_normalization_t ei_data_normalization_config_49 = {
    (void *) &ei_data_normalization_standard_scaler_config_49, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_729880_5_size = 2;
ei_model_dsp_t ei_dsp_blocks_729880_5[ei_dsp_blocks_729880_5_size] = {
    { // DSP block 49
        49,
        14, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_729880_49, // pointer to config struct
        ei_dsp_config_729880_49_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_729880_49_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_49, // data normalization config
    },
    { // DSP block 50
        50,
        10, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_729880_50, // pointer to config struct
        ei_dsp_config_729880_50_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_729880_50_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_729880_47 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_729880_47_init,
    .model_invoke = &tflite_learn_729880_47_invoke,
    .model_reset = &tflite_learn_729880_47_reset,
    .model_input = &tflite_learn_729880_47_input,
    .model_output = &tflite_learn_729880_47_output,
};

const uint8_t ei_output_tensors_indices_729880_47[1] = { 0 };
const uint8_t ei_output_tensors_size_729880_47 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_729880_47 = {
    .implementation_version = 1,
    .block_id = 47,
    .output_tensors_indices = ei_output_tensors_indices_729880_47,
    .output_tensors_size = ei_output_tensors_size_729880_47,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_729880_47,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_729880_5_size = 1;
const uint32_t ei_learning_block_729880_47_inputs[2] = { 49,50 };
const uint8_t ei_learning_block_729880_47_inputs_size = 2;
const ei_learning_block_t ei_learning_blocks_729880_5[ei_learning_blocks_729880_5_size] = {
    {
        47,
        &run_nn_inference,
        (void*)&ei_learning_block_config_729880_47,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_729880_47_inputs,
        ei_learning_block_729880_47_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_729880_47 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_729880_5_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_729880_5[ei_postprocessing_blocks_729880_5_size] = {
    {
        .block_id = 47,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_729880_47,
        .input_block_id = 47
    },
};

const uint8_t freeform_outputs_729880_5_size = 0;

uint32_t *freeform_outputs_729880_5 = nullptr;


const ei_impulse_t impulse_729880_5 = {
    .project_id = 729880,
    .project_owner = "Justin Dax",
    .project_name = "TestForSmokeRekognition",
    .impulse_id = 5,
    .impulse_name = "Impulse #5",
    .deploy_version = 11,

    .nn_input_frame_size = 24,
    .raw_sample_count = 10,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 10 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1000,
    .frequency = 1,

    .dsp_blocks_size = ei_dsp_blocks_729880_5_size,
    .dsp_blocks = ei_dsp_blocks_729880_5,

    .learning_blocks_size = ei_learning_blocks_729880_5_size,
    .learning_blocks = ei_learning_blocks_729880_5,

    .postprocessing_blocks_size = ei_postprocessing_blocks_729880_5_size,
    .postprocessing_blocks = ei_postprocessing_blocks_729880_5,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "temperature + humidity + gas",
    .slice_size = (10/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 8,
    .categories = ei_classifier_inferencing_categories_729880_5,
    .freeform_outputs_size = freeform_outputs_729880_5_size,
    .freeform_outputs = freeform_outputs_729880_5
};

ei_impulse_handle_t impulse_handle_729880_5 = ei_impulse_handle_t( &impulse_729880_5 );
ei_impulse_handle_t& ei_default_impulse = impulse_handle_729880_5;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_729880_5;
const auto ei_dsp_blocks_size = ei_dsp_blocks_729880_5_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_729880_5;

#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
